from pptx import Presentation
from pptx.util import Inches, Pt


class PPTGenerator:

    def generate(self, title: str, slides: list[dict], output_path: str):
        presentation = Presentation()

        # Remove default slide if present
        if presentation.slides:
            slide = presentation.slides[0]
            rId = slide.part.rId
            presentation.part.drop_rel(rId)
            presentation.slides._sldIdLst.remove(
                presentation.slides._sldIdLst[0]
            )

        # Title slide
        title_slide = presentation.slides.add_slide(
            presentation.slide_layouts[0]
        )

        title_slide.shapes.title.text = title

        if len(title_slide.placeholders) > 1:
            title_slide.placeholders[1].text = (
                "Generated by Local Qwen AI"
            )

        # Content slides
        for slide_data in slides:
            slide = presentation.slides.add_slide(
                presentation.slide_layouts[1]
            )

            slide.shapes.title.text = slide_data.get(
                "title",
                "Untitled Slide"
            )

            body = slide.placeholders[1].text_frame
            body.clear()

            bullets = slide_data.get("bullets", [])

            for index, bullet in enumerate(bullets):
                paragraph = (
                    body.paragraphs[0]
                    if index == 0
                    else body.add_paragraph()
                )

                paragraph.text = str(bullet)
                paragraph.level = 0
                paragraph.font.size = Pt(20)

        presentation.save(output_path)